import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../services/group_service.dart';
import '../../theme/app_theme.dart';
import '../../widgets/detail_header.dart';
import '../../widgets/gradient_button.dart';

const _codeLength = 6;

/// Formats typed input as an upper-case invite code, mirroring the
/// codes generated by [InviteMemberScreen].
class _UpperCaseFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    return newValue.copyWith(text: newValue.text.toUpperCase());
  }
}

/// "Join a trip" flow: the counterpart to Invite Member — enter a
/// 6-character code to file a join request with that trip's organizer.
/// Submits via [GroupService.requestToJoin]; the trip only becomes
/// visible once the organizer approves it from Invite Member.
class JoinTripScreen extends StatefulWidget {
  const JoinTripScreen({super.key});

  @override
  State<JoinTripScreen> createState() => _JoinTripScreenState();
}

class _JoinTripScreenState extends State<JoinTripScreen> {
  final _controller = TextEditingController();
  final _groupService = GroupService();
  String _code = '';
  bool _isSubmitting = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  bool get _canJoin => _code.length == _codeLength && !_isSubmitting;

  Future<void> _join() async {
    if (!_canJoin) return;
    setState(() => _isSubmitting = true);
    try {
      await _groupService.requestToJoin(_code);
    } catch (e) {
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(behavior: SnackBarBehavior.floating, content: Text('$e')),
      );
      return;
    }
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        behavior: SnackBarBehavior.floating,
        backgroundColor: context.colors.ink,
        content: const Text('Request sent! Waiting for the organizer to approve.'),
      ),
    );
    Navigator.of(context).maybePop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.colors.surface,
      body: SafeArea(
        child: Column(
          children: [
            DetailHeader(
              title: 'Join a Trip',
              subtitle: 'Enter a friend\'s invite code',
            ),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
                children: [
                  Center(
                    child: Container(
                      width: 72,
                      height: 72,
                      decoration: BoxDecoration(
                        color: AppColors.accent.withValues(alpha: 0.12),
                        shape: BoxShape.circle,
                      ),
                      alignment: Alignment.center,
                      child: const Icon(
                        Icons.group_add_rounded,
                        color: AppColors.accent,
                        size: 32,
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  Text(
                    'Invite Code',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: context.colors.ink,
                      fontWeight: FontWeight.w800,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Ask the trip organizer for their 6-character code',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: context.colors.muted, fontSize: 12.5),
                  ),
                  const SizedBox(height: 22),
                  TextField(
                    controller: _controller,
                    onChanged: (v) => setState(() => _code = v),
                    maxLength: _codeLength,
                    textAlign: TextAlign.center,
                    textCapitalization: TextCapitalization.characters,
                    inputFormatters: [_UpperCaseFormatter()],
                    style: TextStyle(
                      color: context.colors.ink,
                      fontWeight: FontWeight.w900,
                      fontSize: 28,
                      letterSpacing: 10,
                    ),
                    decoration: InputDecoration(
                      counterText: '',
                      hintText: '••••••',
                      hintStyle: TextStyle(
                        color: context.colors.muted.withValues(alpha: 0.4),
                        letterSpacing: 10,
                      ),
                      filled: true,
                      fillColor: context.colors.card,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(18),
                        borderSide: BorderSide.none,
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(18),
                        borderSide: BorderSide(
                          color: context.colors.ink,
                          width: 1.5,
                        ),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        vertical: 18,
                      ),
                    ),
                  ),
                  const SizedBox(height: 28),
                  GradientButton(
                    label: 'Join Trip',
                    icon: Icons.group_add_rounded,
                    onPressed: _canJoin ? () => _join() : () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
