import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../services/locale_service.dart';
import '../../theme/app_theme.dart';
import '../../widgets/detail_header.dart';
import '../../widgets/gradient_button.dart';
import 'group_dashboard_screen.dart';

const _codeLength = 6;

/// Formats typed input as an upper-case invite code, mirroring the
/// codes generated by [InviteMemberScreen].
class _UpperCaseFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    return newValue.copyWith(text: newValue.text.toUpperCase());
  }
}

/// UI-only "join a trip" flow: the counterpart to Invite Member — enter
/// a 6-character code to be added to that trip's group. No backend, so
/// any 6-character code is accepted and lands on the (single) demo
/// trip's group hub.
class JoinTripScreen extends StatefulWidget {
  const JoinTripScreen({super.key});

  @override
  State<JoinTripScreen> createState() => _JoinTripScreenState();
}

class _JoinTripScreenState extends State<JoinTripScreen> {
  final _controller = TextEditingController();
  String _code = '';

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  bool get _canJoin => _code.length == _codeLength;

  Future<void> _join() async {
    if (!_canJoin) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        behavior: SnackBarBehavior.floating,
        backgroundColor: context.colors.ink,
        content: Text(tr('group_joined_snackbar')),
      ),
    );
    await Future.delayed(const Duration(milliseconds: 500));
    if (!mounted) return;
    Navigator.of(
      context,
    ).push(MaterialPageRoute(builder: (_) => const GroupDashboardScreen()));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: context.colors.surface,
      body: SafeArea(
        child: Column(
          children: [
            DetailHeader(
              title: tr('group_join_trip_title'),
              subtitle: tr('group_join_trip_subtitle'),
            ),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.fromLTRB(24, 8, 24, 24),
                children: [
                  Center(
                    child: Container(
                      width: 72,
                      height: 72,
                      decoration: BoxDecoration(
                        color: AppColors.accent.withValues(alpha: 0.12),
                        shape: BoxShape.circle,
                      ),
                      alignment: Alignment.center,
                      child: const Icon(
                        Icons.group_add_rounded,
                        color: AppColors.accent,
                        size: 32,
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),
                  Text(
                    tr('group_invite_code_label'),
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: context.colors.ink,
                      fontWeight: FontWeight.w800,
                      fontSize: 15,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    tr('group_invite_code_ask'),
                    textAlign: TextAlign.center,
                    style: TextStyle(color: context.colors.muted, fontSize: 12.5),
                  ),
                  const SizedBox(height: 22),
                  TextField(
                    controller: _controller,
                    onChanged: (v) => setState(() => _code = v),
                    maxLength: _codeLength,
                    textAlign: TextAlign.center,
                    textCapitalization: TextCapitalization.characters,
                    inputFormatters: [_UpperCaseFormatter()],
                    style: TextStyle(
                      color: context.colors.ink,
                      fontWeight: FontWeight.w900,
                      fontSize: 28,
                      letterSpacing: 10,
                    ),
                    decoration: InputDecoration(
                      counterText: '',
                      hintText: '••••••',
                      hintStyle: TextStyle(
                        color: context.colors.muted.withValues(alpha: 0.4),
                        letterSpacing: 10,
                      ),
                      filled: true,
                      fillColor: context.colors.card,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(18),
                        borderSide: BorderSide.none,
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(18),
                        borderSide: BorderSide(
                          color: context.colors.ink,
                          width: 1.5,
                        ),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        vertical: 18,
                      ),
                    ),
                  ),
                  const SizedBox(height: 28),
                  GradientButton(
                    label: tr('group_join_trip_button'),
                    icon: Icons.group_add_rounded,
                    onPressed: _canJoin ? () => _join() : () {},
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
